
package Unidad01.ListaEjercicios.Ejercicio09;

import Unidad01.ListaEjercicios.Ejercicio10.Menu;
import Unidad01.ListaEjercicios.Ejercicio10.Seleccion;
import java.awt.BorderLayout;

/**
 *
 * @author kgv17
 */
public class Imitador extends javax.swing.JFrame {
    
    /**
     * Creates new form Imitador
     */
    public Imitador() {
        initComponents();
        setLocationRelativeTo(null);
        
        Menu m = new Menu();
        m.setSize(400, 40);

        jPanelMenuImitador.removeAll();
        jPanelMenuImitador.add(m, BorderLayout.CENTER);
        jPanelMenuImitador.revalidate();
        jPanelMenuImitador.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabelOriginal = new javax.swing.JLabel();
        jRadioButtonOpcion1Original = new javax.swing.JRadioButton();
        jRadioButtonOpcion2Original = new javax.swing.JRadioButton();
        jRadioButtonOpcion3Original = new javax.swing.JRadioButton();
        jTextFieldNombreOriginal = new javax.swing.JTextField();
        jComboBoxOriginal = new javax.swing.JComboBox<>();
        jSpinnerOriginal = new javax.swing.JSpinner();
        jSeparatorOriginalEspejo = new javax.swing.JSeparator();
        jLabelEspejo = new javax.swing.JLabel();
        jRadioButtonOpcion1Espejo = new javax.swing.JRadioButton();
        jRadioButtonOpcion2Espejo = new javax.swing.JRadioButton();
        jRadioButtonOpcion3Espejo = new javax.swing.JRadioButton();
        jTextFieldNombreEspejo = new javax.swing.JTextField();
        jComboBoxEspejo = new javax.swing.JComboBox<>();
        jSpinnerEspejo = new javax.swing.JSpinner();
        jCheckBoxOpcion4Original = new javax.swing.JCheckBox();
        jCheckBoxOpcion5Original = new javax.swing.JCheckBox();
        jCheckBoxOpcion6Original = new javax.swing.JCheckBox();
        jCheckBoxOpcion6Espejo = new javax.swing.JCheckBox();
        jCheckBoxOpcion5Espejo = new javax.swing.JCheckBox();
        jCheckBoxOpcion4Espejo = new javax.swing.JCheckBox();
        jPanelMenuImitador = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Imitador");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });

        jLabelOriginal.setText("Original");

        buttonGroup1.add(jRadioButtonOpcion1Original);
        jRadioButtonOpcion1Original.setText("Opcion 1");
        jRadioButtonOpcion1Original.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButtonOpcion1OriginalStateChanged(evt);
            }
        });

        buttonGroup1.add(jRadioButtonOpcion2Original);
        jRadioButtonOpcion2Original.setText("Opcion 2");
        jRadioButtonOpcion2Original.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButtonOpcion2OriginalStateChanged(evt);
            }
        });

        buttonGroup1.add(jRadioButtonOpcion3Original);
        jRadioButtonOpcion3Original.setText("Opcion 3");
        jRadioButtonOpcion3Original.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButtonOpcion3OriginalStateChanged(evt);
            }
        });

        jTextFieldNombreOriginal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNombreOriginalKeyPressed(evt);
            }
        });

        jComboBoxOriginal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxOriginal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxOriginalItemStateChanged(evt);
            }
        });

        jSpinnerOriginal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerOriginalStateChanged(evt);
            }
        });

        jLabelEspejo.setText("Espejo");

        jRadioButtonOpcion1Espejo.setText("Opcion 1");
        jRadioButtonOpcion1Espejo.setEnabled(false);

        jRadioButtonOpcion2Espejo.setText("Opcion 2");
        jRadioButtonOpcion2Espejo.setEnabled(false);

        jRadioButtonOpcion3Espejo.setText("Opcion 3");
        jRadioButtonOpcion3Espejo.setEnabled(false);

        jTextFieldNombreEspejo.setEnabled(false);

        jComboBoxEspejo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxEspejo.setEnabled(false);

        jSpinnerEspejo.setEnabled(false);

        jCheckBoxOpcion4Original.setText("Opcion 4");
        jCheckBoxOpcion4Original.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxOpcion4OriginalStateChanged(evt);
            }
        });

        jCheckBoxOpcion5Original.setText("Opcion 5");
        jCheckBoxOpcion5Original.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxOpcion5OriginalStateChanged(evt);
            }
        });

        jCheckBoxOpcion6Original.setText("Opcion 6");
        jCheckBoxOpcion6Original.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxOpcion6OriginalStateChanged(evt);
            }
        });

        jCheckBoxOpcion6Espejo.setText("Opcion 6");
        jCheckBoxOpcion6Espejo.setEnabled(false);

        jCheckBoxOpcion5Espejo.setText("Opcion 5");
        jCheckBoxOpcion5Espejo.setEnabled(false);

        jCheckBoxOpcion4Espejo.setText("Opcion 4");
        jCheckBoxOpcion4Espejo.setEnabled(false);

        jPanelMenuImitador.setMinimumSize(new java.awt.Dimension(400, 40));
        jPanelMenuImitador.setPreferredSize(new java.awt.Dimension(400, 40));

        javax.swing.GroupLayout jPanelMenuImitadorLayout = new javax.swing.GroupLayout(jPanelMenuImitador);
        jPanelMenuImitador.setLayout(jPanelMenuImitadorLayout);
        jPanelMenuImitadorLayout.setHorizontalGroup(
            jPanelMenuImitadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelMenuImitadorLayout.setVerticalGroup(
            jPanelMenuImitadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonOpcion1Original)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxOpcion4Original))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonOpcion3Original)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxOpcion6Original))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonOpcion2Original)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxOpcion5Original))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonOpcion2Espejo)
                                    .addComponent(jRadioButtonOpcion3Espejo)
                                    .addComponent(jRadioButtonOpcion1Espejo))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxOpcion6Espejo)
                                    .addComponent(jCheckBoxOpcion5Espejo)
                                    .addComponent(jCheckBoxOpcion4Espejo))))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSpinnerOriginal, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxOriginal, 0, 108, Short.MAX_VALUE)
                            .addComponent(jTextFieldNombreOriginal)
                            .addComponent(jTextFieldNombreEspejo)
                            .addComponent(jComboBoxEspejo, 0, 0, Short.MAX_VALUE)
                            .addComponent(jSpinnerEspejo, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelEspejo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelOriginal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(38, 38, 38))
            .addComponent(jPanelMenuImitador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparatorOriginalEspejo)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelMenuImitador, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelOriginal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonOpcion1Original)
                    .addComponent(jTextFieldNombreOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxOpcion4Original))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonOpcion3Original)
                            .addComponent(jCheckBoxOpcion6Original)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonOpcion2Original)
                        .addComponent(jCheckBoxOpcion5Original))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jComboBoxOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinnerOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(jSeparatorOriginalEspejo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabelEspejo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonOpcion1Espejo)
                            .addComponent(jTextFieldNombreEspejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jRadioButtonOpcion3Espejo))
                            .addComponent(jRadioButtonOpcion2Espejo)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jComboBoxEspejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinnerEspejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBoxOpcion4Espejo)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jCheckBoxOpcion6Espejo))
                            .addComponent(jCheckBoxOpcion5Espejo))))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonOpcion1OriginalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonOpcion1OriginalStateChanged
        jRadioButtonOpcion1Espejo.setSelected(jRadioButtonOpcion1Original.isSelected());
    }//GEN-LAST:event_jRadioButtonOpcion1OriginalStateChanged

    private void jRadioButtonOpcion2OriginalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonOpcion2OriginalStateChanged
        jRadioButtonOpcion2Espejo.setSelected(jRadioButtonOpcion2Original.isSelected());
    }//GEN-LAST:event_jRadioButtonOpcion2OriginalStateChanged

    private void jRadioButtonOpcion3OriginalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonOpcion3OriginalStateChanged
        jRadioButtonOpcion3Espejo.setSelected(jRadioButtonOpcion3Original.isSelected());
    }//GEN-LAST:event_jRadioButtonOpcion3OriginalStateChanged

    private void jCheckBoxOpcion4OriginalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxOpcion4OriginalStateChanged
        jCheckBoxOpcion4Espejo.setSelected(jCheckBoxOpcion4Original.isSelected());
    }//GEN-LAST:event_jCheckBoxOpcion4OriginalStateChanged

    private void jCheckBoxOpcion5OriginalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxOpcion5OriginalStateChanged
        jCheckBoxOpcion5Espejo.setSelected(jCheckBoxOpcion5Original.isSelected());
    }//GEN-LAST:event_jCheckBoxOpcion5OriginalStateChanged

    private void jCheckBoxOpcion6OriginalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxOpcion6OriginalStateChanged
        jCheckBoxOpcion6Espejo.setSelected(jCheckBoxOpcion6Original.isSelected());
    }//GEN-LAST:event_jCheckBoxOpcion6OriginalStateChanged

    private void jTextFieldNombreOriginalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreOriginalKeyPressed
        jTextFieldNombreEspejo.setText(jTextFieldNombreOriginal.getText());
    }//GEN-LAST:event_jTextFieldNombreOriginalKeyPressed

    private void jComboBoxOriginalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxOriginalItemStateChanged
        jComboBoxEspejo.setSelectedItem(jComboBoxOriginal.getSelectedItem());
    }//GEN-LAST:event_jComboBoxOriginalItemStateChanged

    private void jSpinnerOriginalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerOriginalStateChanged
        jSpinnerEspejo.setValue(jSpinnerOriginal.getValue());
    }//GEN-LAST:event_jSpinnerOriginalStateChanged

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // s.setTitle("Todos para uno y uno para todos");
    }//GEN-LAST:event_formWindowClosed

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        dispose();
    }//GEN-LAST:event_formWindowDeactivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Imitador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Imitador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Imitador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Imitador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Imitador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCheckBoxOpcion4Espejo;
    private javax.swing.JCheckBox jCheckBoxOpcion4Original;
    private javax.swing.JCheckBox jCheckBoxOpcion5Espejo;
    private javax.swing.JCheckBox jCheckBoxOpcion5Original;
    private javax.swing.JCheckBox jCheckBoxOpcion6Espejo;
    private javax.swing.JCheckBox jCheckBoxOpcion6Original;
    private javax.swing.JComboBox<String> jComboBoxEspejo;
    private javax.swing.JComboBox<String> jComboBoxOriginal;
    private javax.swing.JLabel jLabelEspejo;
    private javax.swing.JLabel jLabelOriginal;
    private javax.swing.JPanel jPanelMenuImitador;
    private javax.swing.JRadioButton jRadioButtonOpcion1Espejo;
    private javax.swing.JRadioButton jRadioButtonOpcion1Original;
    private javax.swing.JRadioButton jRadioButtonOpcion2Espejo;
    private javax.swing.JRadioButton jRadioButtonOpcion2Original;
    private javax.swing.JRadioButton jRadioButtonOpcion3Espejo;
    private javax.swing.JRadioButton jRadioButtonOpcion3Original;
    private javax.swing.JSeparator jSeparatorOriginalEspejo;
    private javax.swing.JSpinner jSpinnerEspejo;
    private javax.swing.JSpinner jSpinnerOriginal;
    private javax.swing.JTextField jTextFieldNombreEspejo;
    private javax.swing.JTextField jTextFieldNombreOriginal;
    // End of variables declaration//GEN-END:variables
}
