
package Unidad01.EjemploJFileChooser;

import java.io.File;
import javax.swing.*;
import javax.swing.JOptionPane;

/**
 *
 * @author kgv17
 */
public class EjemploFileChooser extends javax.swing.JFrame {

    /**
     * Creates new form ejemploFileChooser
     */
    public EjemploFileChooser() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextFieldInformacion = new javax.swing.JTextField();
        jButtonAceptar = new javax.swing.JButton();
        jRadioButtonFicheros = new javax.swing.JRadioButton();
        jRadioButtonDirectorios = new javax.swing.JRadioButton();
        jRadioButtonAmbos = new javax.swing.JRadioButton();
        jLabelTexto = new javax.swing.JLabel();
        jLabelSeleccion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Selección");

        jTextFieldInformacion.setEditable(false);

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonFicheros);
        jRadioButtonFicheros.setText("Ficheros");

        buttonGroup1.add(jRadioButtonDirectorios);
        jRadioButtonDirectorios.setText("Directorios");

        buttonGroup1.add(jRadioButtonAmbos);
        jRadioButtonAmbos.setText("Ambos");

        jLabelTexto.setText("Escoja una opción:");

        jLabelSeleccion.setText("Selección:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTexto)
                            .addComponent(jRadioButtonFicheros)
                            .addComponent(jRadioButtonAmbos)
                            .addComponent(jRadioButtonDirectorios))
                        .addContainerGap(347, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSeleccion)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonAceptar)
                                .addComponent(jTextFieldInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabelTexto)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonFicheros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonDirectorios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonAmbos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabelSeleccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAceptar)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        
        JFileChooser jfc = new JFileChooser();
        jfc.setMultiSelectionEnabled(true);
        String textoLabel = this.jLabelTexto.getText();
        jfc.setDialogTitle(textoLabel.substring(0, textoLabel.length() - 1));

        if (this.buttonGroup1.getSelection() != null) {
            // Establecer el modo de selección basado en el botón de opción seleccionado
            if (this.jRadioButtonFicheros.isSelected()) {
                jfc.setFileSelectionMode(JFileChooser.FILES_ONLY);
                this.jLabelSeleccion.setText("Fichero/s seleccionado/s:");
            } else if (this.jRadioButtonDirectorios.isSelected()) {
                jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                this.jLabelSeleccion.setText("Directorio/s seleccionado/s:");
            } else {
                jfc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
                this.jLabelSeleccion.setText("Fichero/s y Directorio/s seleccionados:");
            }

            int returnValue = jfc.showDialog(this, "Seleccionar");

            if (returnValue == JFileChooser.APPROVE_OPTION) {
                File[] selectedFiles = jfc.getSelectedFiles();

                // Limpiar el campo de texto antes de mostrar los nombres
                this.jTextFieldInformacion.setText(""); 

                // Usar StringBuilder para acumular nombres
                StringBuilder fileNames = new StringBuilder();

                for (File selectedFile : selectedFiles) {
                    // Añadir el nombre del archivo o directorio al StringBuilder
                    if (fileNames.length() > 0) {
                        fileNames.append(", "); // Añadir coma entre nombres
                    }
                    fileNames.append(selectedFile.getName());
                }

                // Establecer el texto acumulado en el JTextField
                this.jTextFieldInformacion.setText(fileNames.toString());
            } 
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione una opción", "Alerta", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_jButtonAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EjemploFileChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EjemploFileChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EjemploFileChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EjemploFileChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EjemploFileChooser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JLabel jLabelSeleccion;
    private javax.swing.JLabel jLabelTexto;
    private javax.swing.JRadioButton jRadioButtonAmbos;
    private javax.swing.JRadioButton jRadioButtonDirectorios;
    private javax.swing.JRadioButton jRadioButtonFicheros;
    private javax.swing.JTextField jTextFieldInformacion;
    // End of variables declaration//GEN-END:variables
}
