package Unidad01.EjemploApp;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JSeparator;

/**
 *
 * @author kgv17
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private boolean b;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        crearPopupMenu();
        flasheableLabel();
    }

    private void crearPopupMenu() {
        JMenuItem abrir = new JMenuItem("Abrir", getIcon("/Unidad01/EjemploApp/Icons/abrir.png", 20, 20));
        JMenuItem guardar = new JMenuItem("Guardar", getIcon("/Unidad01/EjemploApp/Icons/guardar.png", 20, 20));
        JMenuItem salir = new JMenuItem("Salir", getIcon("/Unidad01/EjemploApp/Icons/salir.png", 20, 20));
        JSeparator separador1 = new JSeparator();
        JSeparator separador2 = new JSeparator();
        jPopupMenu1.add(abrir);
        jPopupMenu1.add(separador1);
        jPopupMenu1.add(guardar);
        jPopupMenu1.add(separador2);
        jPopupMenu1.add(salir);
        jPanel1.setComponentPopupMenu(jPopupMenu1);

        abrir.addActionListener((ActionEvent ae) -> {
            JOptionPane.showMessageDialog(abrir, "HAS PULSADO ABRIR");
        });
        guardar.addActionListener((ActionEvent ae) -> {
            JOptionPane.showMessageDialog(guardar, "HAS PULSADO GUARDAR");
        });
        salir.addActionListener((ActionEvent ae) -> {
            JOptionPane.showMessageDialog(guardar, "HAS PULSADO SALIR");
            System.exit(0); // Cierra la aplicación.
        });

    }

    private Icon getIcon(String ruta, int ancho, int alto) {
        try {
            return new ImageIcon(new ImageIcon(getClass().getResource(ruta)).getImage()
                    .getScaledInstance(ancho, alto, java.awt.Image.SCALE_SMOOTH));
        } catch (NullPointerException e) {
            System.err.println("Icon not found: " + ruta);
            return null; // Devuelve null si no se encuentra el recurso.
        }
    }
    
    private void flasheableLabel(){
        Timer reloj = new Timer();
        
        TimerTask flash;
        jLabel1.setOpaque(true);
        flash = new TimerTask(){
            @Override
            public void run(){
                if (b) {
                    jLabel1.setBackground(Color.black);
                    jLabel1.setForeground(Color.white);
                }else{
                    jLabel1.setBackground(Color.white);
                    jLabel1.setForeground(Color.black);
                    
                }
                b=(!b);
                
            }
        };
        reloj.schedule(flash, new Date() ,800);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("  Ejemplo.txt");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 278, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
