
package Unidad01.ListaEjercicios.Ejercicio06;

import java.awt.Frame;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author kgv17
 */
public class Registro extends javax.swing.JDialog {

    private Exito e;
    private AñadirHijo ah;
    
    /**
     * Creates new form Registro
     * @param parent
     * @param modal
     */
    public Registro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        DefaultTableModel model = (DefaultTableModel) jTableTabla.getModel();
        model.addRow(new Object[]{"Nombre", "Apellidos", "FechaNacimiento", "Deporte", "Nivel"});


        jScrollPane2.setVisible(false);
        jTableTabla.setVisible(false);
        this.jTableTabla.setModel(model);
        
        this.revalidate();         // Reorganiza el diseño del contenedor
        this.repaint();            // Redibuja el contenedor
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelSeleccionDeporte = new javax.swing.JPanel();
        jComboBoxDeportes = new javax.swing.JComboBox<>();
        jLabelDeporte = new javax.swing.JLabel();
        jSpinnerNivel = new javax.swing.JSpinner();
        jLabelTurno = new javax.swing.JLabel();
        jLabelRenovación = new javax.swing.JLabel();
        jRadioButtonMañana = new javax.swing.JRadioButton();
        jRadioButtonTarde = new javax.swing.JRadioButton();
        jCheckBoxAnual = new javax.swing.JCheckBox();
        jCheckBoxTrimestral = new javax.swing.JCheckBox();
        jPanelHijos = new javax.swing.JPanel();
        jButtonAñadirHijo = new javax.swing.JButton();
        jButtonVerOcultaTabla = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTabla = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelNivel = new javax.swing.JLabel();
        jButtonMatricular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro Deportivo");
        setMaximumSize(new java.awt.Dimension(500, 2147483647));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));
        setSize(new java.awt.Dimension(500, 500));

        jLabelTitulo.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabelTitulo.setText("REGISTRO DEPORTIVO");
        jLabelTitulo.setMaximumSize(new java.awt.Dimension(325, 35));
        jLabelTitulo.setMinimumSize(new java.awt.Dimension(325, 35));
        jLabelTitulo.setPreferredSize(new java.awt.Dimension(325, 35));

        jPanelSeleccionDeporte.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Selección deporte", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));
        jPanelSeleccionDeporte.setMinimumSize(new java.awt.Dimension(430, 350));
        jPanelSeleccionDeporte.setPreferredSize(new java.awt.Dimension(430, 350));

        jComboBoxDeportes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tenis", "Padel", "Squash" }));
        jComboBoxDeportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDeportesActionPerformed(evt);
            }
        });

        jLabelDeporte.setText("Deporte");

        jSpinnerNivel.setModel(new javax.swing.SpinnerListModel(new String[] {"Inicial", "Medio", "Avanzado", "Profesional"}));

        jLabelTurno.setText("Turno");

        jLabelRenovación.setText("Renovación");

        buttonGroup1.add(jRadioButtonMañana);
        jRadioButtonMañana.setText("Mañana");

        buttonGroup1.add(jRadioButtonTarde);
        jRadioButtonTarde.setText("Tarde");

        jCheckBoxAnual.setText("Anual");

        jCheckBoxTrimestral.setText("Trimestral");

        jPanelHijos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hijos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        jButtonAñadirHijo.setText("Añadir Hijo");
        jButtonAñadirHijo.setMaximumSize(new java.awt.Dimension(100, 23));
        jButtonAñadirHijo.setMinimumSize(new java.awt.Dimension(100, 23));
        jButtonAñadirHijo.setPreferredSize(new java.awt.Dimension(100, 23));
        jButtonAñadirHijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirHijoActionPerformed(evt);
            }
        });

        jButtonVerOcultaTabla.setText("Ver tabla");
        jButtonVerOcultaTabla.setMaximumSize(new java.awt.Dimension(100, 23));
        jButtonVerOcultaTabla.setMinimumSize(new java.awt.Dimension(100, 23));
        jButtonVerOcultaTabla.setPreferredSize(new java.awt.Dimension(100, 23));
        jButtonVerOcultaTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerOcultaTablaActionPerformed(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setMaximumSize(new java.awt.Dimension(380, 32767));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(357, 50));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(357, 50));

        jTableTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableTabla.setMaximumSize(new java.awt.Dimension(400, 200));
        jTableTabla.setMinimumSize(new java.awt.Dimension(380, 200));
        jTableTabla.setPreferredSize(new java.awt.Dimension(380, 200));
        jScrollPane2.setViewportView(jTableTabla);

        javax.swing.GroupLayout jPanelHijosLayout = new javax.swing.GroupLayout(jPanelHijos);
        jPanelHijos.setLayout(jPanelHijosLayout);
        jPanelHijosLayout.setHorizontalGroup(
            jPanelHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHijosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelHijosLayout.createSequentialGroup()
                        .addComponent(jButtonVerOcultaTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157)
                        .addComponent(jButtonAñadirHijo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanelHijosLayout.setVerticalGroup(
            jPanelHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHijosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVerOcultaTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAñadirHijo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator1.setMaximumSize(new java.awt.Dimension(400, 3));
        jSeparator1.setMinimumSize(new java.awt.Dimension(400, 3));
        jSeparator1.setPreferredSize(new java.awt.Dimension(400, 3));

        jLabelNivel.setText("Nivel");

        javax.swing.GroupLayout jPanelSeleccionDeporteLayout = new javax.swing.GroupLayout(jPanelSeleccionDeporte);
        jPanelSeleccionDeporte.setLayout(jPanelSeleccionDeporteLayout);
        jPanelSeleccionDeporteLayout.setHorizontalGroup(
            jPanelSeleccionDeporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeleccionDeporteLayout.createSequentialGroup()
                .addGroup(jPanelSeleccionDeporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSeleccionDeporteLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelSeleccionDeporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSeleccionDeporteLayout.createSequentialGroup()
                                .addComponent(jRadioButtonTarde)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelSeleccionDeporteLayout.createSequentialGroup()
                                .addComponent(jLabelDeporte)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxDeportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabelNivel))
                    .addGroup(jPanelSeleccionDeporteLayout.createSequentialGroup()
                        .addGroup(jPanelSeleccionDeporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSeleccionDeporteLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabelTurno))
                            .addGroup(jPanelSeleccionDeporteLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jRadioButtonMañana)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSeleccionDeporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRenovación)
                    .addComponent(jSpinnerNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxTrimestral)
                    .addComponent(jCheckBoxAnual))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelSeleccionDeporteLayout.createSequentialGroup()
                .addComponent(jPanelHijos, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelSeleccionDeporteLayout.setVerticalGroup(
            jPanelSeleccionDeporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeleccionDeporteLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelSeleccionDeporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDeporte)
                    .addComponent(jComboBoxDeportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNivel)
                    .addComponent(jSpinnerNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanelSeleccionDeporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTurno)
                    .addComponent(jLabelRenovación))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSeleccionDeporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonMañana)
                    .addComponent(jCheckBoxTrimestral))
                .addGap(5, 5, 5)
                .addGroup(jPanelSeleccionDeporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonTarde)
                    .addComponent(jCheckBoxAnual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelHijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        jButtonMatricular.setText("MATRICULAR");
        jButtonMatricular.setMaximumSize(new java.awt.Dimension(450, 23));
        jButtonMatricular.setMinimumSize(new java.awt.Dimension(450, 23));
        jButtonMatricular.setPreferredSize(new java.awt.Dimension(450, 23));
        jButtonMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMatricularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelSeleccionDeporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMatricular, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelSeleccionDeporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonMatricular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void añadirPersona(Persona p){
        DefaultTableModel modeloTabla = (DefaultTableModel) jTableTabla.getModel();
        modeloTabla.addRow(p.toArrayString());
    }
    
    private void jComboBoxDeportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDeportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDeportesActionPerformed

    private void jButtonMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMatricularActionPerformed
        e = new Exito((Frame) this.getParent(), true);
        e.setVisible(true);
    }//GEN-LAST:event_jButtonMatricularActionPerformed

    private void jButtonVerOcultaTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerOcultaTablaActionPerformed

        // Verifica si la tabla está actualmente visible
        if (jScrollPane2.isVisible()) {
            // Si es visible, ocúltala
            jScrollPane2.setVisible(false);
            jButtonVerOcultaTabla.setText("Ver tabla"); // Cambia el texto del botón
        } else {
            // Si no es visible, muéstrala
            jScrollPane2.setVisible(true);
            jButtonVerOcultaTabla.setText("Ocultar tabla"); // Cambia el texto del botón
        }

        // Actualiza el layout para reflejar los cambios
        revalidate();
        repaint();
    }//GEN-LAST:event_jButtonVerOcultaTablaActionPerformed

    private void jButtonAñadirHijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirHijoActionPerformed
        ah = new AñadirHijo((Frame) getParent(), true);
        ah.setVisible(true);
    }//GEN-LAST:event_jButtonAñadirHijoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            Registro dialog = new Registro(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonAñadirHijo;
    private javax.swing.JButton jButtonMatricular;
    private javax.swing.JButton jButtonVerOcultaTabla;
    private javax.swing.JCheckBox jCheckBoxAnual;
    private javax.swing.JCheckBox jCheckBoxTrimestral;
    private javax.swing.JComboBox<String> jComboBoxDeportes;
    private javax.swing.JLabel jLabelDeporte;
    private javax.swing.JLabel jLabelNivel;
    private javax.swing.JLabel jLabelRenovación;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTurno;
    private javax.swing.JPanel jPanelHijos;
    private javax.swing.JPanel jPanelSeleccionDeporte;
    private javax.swing.JRadioButton jRadioButtonMañana;
    private javax.swing.JRadioButton jRadioButtonTarde;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinnerNivel;
    private javax.swing.JTable jTableTabla;
    // End of variables declaration//GEN-END:variables
}
