
package Unidad01.ListaEjercicios.Ejercicio06;

import java.awt.Frame;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author kgv17
 */
public class Registro extends javax.swing.JDialog {

    private Exito ex;
    private final Error er;
    private AñadirHijo ah;
    public static LogicaPersonas logicaPersonas = new LogicaPersonas();
    
    /**
     * Creates new form Registro
     * @param parent
     * @param modal
     */
    public Registro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        refrescarTabla();
        
        er = new Error((Frame) this.getParent(), true, "Por favor complete todos los campos.");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelSeleccionDeporte = new javax.swing.JPanel();
        jPanelHijos = new javax.swing.JPanel();
        jButtonAñadirHijo = new javax.swing.JButton();
        jButtonVerOcultaTabla = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTabla = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabelDeporte = new javax.swing.JLabel();
        jComboBoxDeportes = new javax.swing.JComboBox<>();
        jLabelTurno = new javax.swing.JLabel();
        jRadioButtonMañana = new javax.swing.JRadioButton();
        jRadioButtonTarde = new javax.swing.JRadioButton();
        jLabelRenovación = new javax.swing.JLabel();
        jLabelNivel = new javax.swing.JLabel();
        jCheckBoxAnual = new javax.swing.JCheckBox();
        jCheckBoxTrimestral = new javax.swing.JCheckBox();
        jSpinnerNivel = new javax.swing.JSpinner();
        jButtonMatricular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro Deportivo");
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));
        setSize(new java.awt.Dimension(500, 500));

        jLabelTitulo.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabelTitulo.setText("REGISTRO DEPORTIVO");
        jLabelTitulo.setMaximumSize(new java.awt.Dimension(325, 35));
        jLabelTitulo.setMinimumSize(new java.awt.Dimension(325, 35));
        jLabelTitulo.setPreferredSize(new java.awt.Dimension(325, 35));

        jPanelSeleccionDeporte.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Selección deporte", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));
        jPanelSeleccionDeporte.setMaximumSize(new java.awt.Dimension(480, 350));
        jPanelSeleccionDeporte.setMinimumSize(new java.awt.Dimension(480, 350));
        jPanelSeleccionDeporte.setPreferredSize(new java.awt.Dimension(480, 350));

        jPanelHijos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hijos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));
        jPanelHijos.setMaximumSize(new java.awt.Dimension(460, 80));
        jPanelHijos.setMinimumSize(new java.awt.Dimension(460, 80));
        jPanelHijos.setPreferredSize(new java.awt.Dimension(460, 80));

        jButtonAñadirHijo.setText("Añadir Hijo");
        jButtonAñadirHijo.setMaximumSize(new java.awt.Dimension(100, 23));
        jButtonAñadirHijo.setMinimumSize(new java.awt.Dimension(100, 23));
        jButtonAñadirHijo.setPreferredSize(new java.awt.Dimension(100, 23));
        jButtonAñadirHijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirHijoActionPerformed(evt);
            }
        });

        jButtonVerOcultaTabla.setText("Ver tabla");
        jButtonVerOcultaTabla.setMaximumSize(new java.awt.Dimension(100, 23));
        jButtonVerOcultaTabla.setMinimumSize(new java.awt.Dimension(100, 23));
        jButtonVerOcultaTabla.setPreferredSize(new java.awt.Dimension(100, 23));
        jButtonVerOcultaTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerOcultaTablaActionPerformed(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setMaximumSize(new java.awt.Dimension(300, 60));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(300, 60));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(300, 60));

        jTableTabla.setMaximumSize(new java.awt.Dimension(300, 60));
        jTableTabla.setMinimumSize(new java.awt.Dimension(300, 60));
        jTableTabla.setPreferredSize(new java.awt.Dimension(300, 60));
        jTableTabla.getTableHeader().setResizingAllowed(false);
        jScrollPane2.setViewportView(jTableTabla);

        javax.swing.GroupLayout jPanelHijosLayout = new javax.swing.GroupLayout(jPanelHijos);
        jPanelHijos.setLayout(jPanelHijosLayout);
        jPanelHijosLayout.setHorizontalGroup(
            jPanelHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHijosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelHijosLayout.createSequentialGroup()
                        .addComponent(jButtonVerOcultaTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jButtonAñadirHijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHijosLayout.setVerticalGroup(
            jPanelHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHijosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVerOcultaTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAñadirHijo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.setMaximumSize(new java.awt.Dimension(450, 130));
        jPanel1.setMinimumSize(new java.awt.Dimension(450, 130));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 130));

        jLabelDeporte.setText("Deporte");

        jComboBoxDeportes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tenis", "Padel", "Squash" }));

        jLabelTurno.setText("Turno");

        buttonGroup1.add(jRadioButtonMañana);
        jRadioButtonMañana.setText("Mañana");

        buttonGroup1.add(jRadioButtonTarde);
        jRadioButtonTarde.setText("Tarde");

        jLabelRenovación.setText("Renovación");

        jLabelNivel.setText("Nivel");

        jCheckBoxAnual.setText("Anual");

        jCheckBoxTrimestral.setText("Trimestral");

        jSpinnerNivel.setModel(new javax.swing.SpinnerListModel(new String[] {"Inicial", "Medio", "Avanzado", "Profesional"}));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelDeporte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonMañana)
                            .addComponent(jRadioButtonTarde)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBoxDeportes, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jLabelRenovación)))
                        .addGap(5, 5, 5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabelTurno)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelNivel)
                        .addGap(6, 6, 6)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxTrimestral)
                    .addComponent(jCheckBoxAnual, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDeporte)
                    .addComponent(jComboBoxDeportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRenovación)
                    .addComponent(jSpinnerNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTurno)
                    .addComponent(jLabelNivel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonMañana)
                    .addComponent(jCheckBoxAnual))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonTarde)
                    .addComponent(jCheckBoxTrimestral))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelSeleccionDeporteLayout = new javax.swing.GroupLayout(jPanelSeleccionDeporte);
        jPanelSeleccionDeporte.setLayout(jPanelSeleccionDeporteLayout);
        jPanelSeleccionDeporteLayout.setHorizontalGroup(
            jPanelSeleccionDeporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeleccionDeporteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelSeleccionDeporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelHijos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSeleccionDeporteLayout.setVerticalGroup(
            jPanelSeleccionDeporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeleccionDeporteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelHijos, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonMatricular.setText("MATRICULAR");
        jButtonMatricular.setMaximumSize(new java.awt.Dimension(450, 23));
        jButtonMatricular.setMinimumSize(new java.awt.Dimension(450, 23));
        jButtonMatricular.setPreferredSize(new java.awt.Dimension(450, 23));
        jButtonMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMatricularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jPanelSeleccionDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonMatricular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSeleccionDeporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonMatricular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void refrescarTabla(){
        DefaultTableModel modeloTabla = new DefaultTableModel();
        modeloTabla.setColumnIdentifiers(new String[] {"Nombre", "Apellidos", "Fecha", "Deporte", "Nivel"});
        jTableTabla.setModel(modeloTabla);
        
        // Coje la lista de la clase LogicaNegocio y añade los clientes a la tabla
        List<Persona> listaPersonas = logicaPersonas.getListaPersonas();
        for (Persona persona : listaPersonas) {
            modeloTabla.addRow(persona.toArrayString());
        }
        
        jTableTabla.setVisible(false);
        jScrollPane2.setVisible(false);
        this.revalidate();         
        this.repaint();           
        
    }
    
    private void jButtonMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMatricularActionPerformed

        if (buttonGroup1.getSelection() == null) {
            er.setVisible(true); 
            
        }else if (!jCheckBoxAnual.isSelected() && !jCheckBoxTrimestral.isSelected()) {
            er.setVisible(true);  
            
        }
        else {
            ex = new Exito((Frame) this.getParent(), true);
            ex.setVisible(true);
        }
        
    }//GEN-LAST:event_jButtonMatricularActionPerformed

    private void jButtonVerOcultaTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerOcultaTablaActionPerformed

        // Verifica si la tabla está actualmente visible
        if (jScrollPane2.isVisible()) {
            // Si es visible, ocúltala
            jScrollPane2.setVisible(false);
            jTableTabla.setVisible(false);
            jButtonVerOcultaTabla.setText("Ver tabla"); // Cambia el texto del botón
        } else {
            // Si no es visible, muéstrala
            jScrollPane2.setVisible(true);
            jTableTabla.setVisible(true);
            jButtonVerOcultaTabla.setText("Ocultar tabla"); // Cambia el texto del botón
        }

        // Actualiza el layout para reflejar los cambios
        revalidate();
        repaint();
    }//GEN-LAST:event_jButtonVerOcultaTablaActionPerformed

    private void jButtonAñadirHijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirHijoActionPerformed
        // dispose();
        ah = new AñadirHijo((Frame) getParent(), true);
        ah.setVisible(true);
        refrescarTabla();
    }//GEN-LAST:event_jButtonAñadirHijoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            Registro dialog = new Registro(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAñadirHijo;
    private javax.swing.JButton jButtonMatricular;
    private javax.swing.JButton jButtonVerOcultaTabla;
    private javax.swing.JCheckBox jCheckBoxAnual;
    private javax.swing.JCheckBox jCheckBoxTrimestral;
    private javax.swing.JComboBox<String> jComboBoxDeportes;
    private javax.swing.JLabel jLabelDeporte;
    private javax.swing.JLabel jLabelNivel;
    private javax.swing.JLabel jLabelRenovación;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTurno;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelHijos;
    private javax.swing.JPanel jPanelSeleccionDeporte;
    private javax.swing.JRadioButton jRadioButtonMañana;
    private javax.swing.JRadioButton jRadioButtonTarde;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerNivel;
    private javax.swing.JTable jTableTabla;
    // End of variables declaration//GEN-END:variables
}
