package Main.Dialogs;

import Controllers.Controller;
import Main.Frame.VentanaPrincipal;
import Entities.Usuario;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Map;

/**
 * 
 * @author Kevin e Iván
 */
public class AccesoUsuario extends javax.swing.JDialog {

    private final VentanaPrincipal ventanaPrincipal;
    private final CrearCuenta crearCuenta;
    public static ArrayList<Usuario> usuarios = new ArrayList<>();
    public Usuario usuarioLogeado;

    /**
     * Creates new form AccesoUsuario
     *
     * @param parent
     * @param modal
     */
    public AccesoUsuario(java.awt.Frame parent, boolean modal) {
 
        super(parent, modal);
        this.ventanaPrincipal = (VentanaPrincipal) parent;
        this.crearCuenta = new CrearCuenta(parent, true);
        initComponents();
        setLocationRelativeTo(null);

        subrayarLabel();

        crearUsuarioEjemplo();
 
    }

    private void crearUsuarioEjemplo(){
        char[] contraseña = "passwd".toCharArray();
        Usuario usuario = new Usuario("Victor", "Sanchez", "user", contraseña, "user@hotmail.com", 601479874, "España/Granada", "Pedro Antonio 13", "4ºC");
        AccesoUsuario.usuarios.add(usuario);
        
        this.jTextFieldUsuario.setText(usuario.getNombreUsuario());
        this.jPasswordFieldContraseña.setText("passwd");
    }
    
    private void subrayarLabel() {
        // Subrayar label crear
        Font currentFont = this.jLabelCrear.getFont();
        Map<TextAttribute, Object> attributes = (Map<TextAttribute, Object>) currentFont.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        this.jLabelCrear.setFont(currentFont.deriveFont(attributes));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Ed&itor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelMain = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabelUsuarioIncorrecto = new javax.swing.JLabel();
        jLabelContraseña = new javax.swing.JLabel();
        jPasswordFieldContraseña = new javax.swing.JPasswordField();
        jLabelNoCuenta = new javax.swing.JLabel();
        jLabelCrear = new javax.swing.JLabel();
        jButtonIniciarSesion = new javax.swing.JButton();
        jLabelContraseñaIncorrecta = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FastEat: Inicio de Sesión");
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(204, 204, 204));
        setSize(new java.awt.Dimension(400, 450));

        jPanelMain.setBackground(new java.awt.Color(51, 51, 51));

        jLabelTitulo.setFont(new java.awt.Font("MS Gothic", 1, 55)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 102, 0));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("FAST EAT");

        jLabelUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(204, 204, 204));
        jLabelUsuario.setText("Usuario");

        jTextFieldUsuario.setBackground(new java.awt.Color(102, 102, 102));
        jTextFieldUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldUsuario.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldUsuarioKeyPressed(evt);
            }
        });

        jLabelUsuarioIncorrecto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelUsuarioIncorrecto.setForeground(new java.awt.Color(204, 51, 0));
        jLabelUsuarioIncorrecto.setText(" ");
        jLabelUsuarioIncorrecto.setToolTipText("");

        jLabelContraseña.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelContraseña.setForeground(new java.awt.Color(204, 204, 204));
        jLabelContraseña.setText("Contraseña");

        jPasswordFieldContraseña.setBackground(new java.awt.Color(102, 102, 102));
        jPasswordFieldContraseña.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPasswordFieldContraseña.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordFieldContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldContraseñaKeyPressed(evt);
            }
        });

        jLabelNoCuenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNoCuenta.setForeground(new java.awt.Color(153, 153, 153));
        jLabelNoCuenta.setText("¿No tienes cuenta?");

        jLabelCrear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCrear.setForeground(new java.awt.Color(153, 153, 153));
        jLabelCrear.setText("Crear");
        jLabelCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCrearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCrearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCrearMouseExited(evt);
            }
        });

        jButtonIniciarSesion.setBackground(new java.awt.Color(255, 102, 0));
        jButtonIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonIniciarSesion.setForeground(new java.awt.Color(0, 0, 0));
        jButtonIniciarSesion.setText("INICIAR SESIÓN");
        jButtonIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonIniciarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonIniciarSesionMouseExited(evt);
            }
        });
        jButtonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarSesionActionPerformed(evt);
            }
        });

        jLabelContraseñaIncorrecta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelContraseñaIncorrecta.setForeground(new java.awt.Color(204, 51, 0));
        jLabelContraseñaIncorrecta.setText(" ");

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(0, 44, Short.MAX_VALUE)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelUsuario)
                            .addComponent(jLabelContraseña)
                            .addComponent(jPasswordFieldContraseña)
                            .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jLabelUsuarioIncorrecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelContraseñaIncorrecta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelMainLayout.createSequentialGroup()
                                .addComponent(jLabelNoCuenta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCrear)
                                .addGap(26, 26, 26)
                                .addComponent(jButtonIniciarSesion)))
                        .addGap(0, 44, Short.MAX_VALUE))
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addGap(28, 28, 28)
                .addComponent(jLabelUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUsuarioIncorrecto)
                .addGap(18, 18, 18)
                .addComponent(jLabelContraseña)
                .addGap(15, 15, 15)
                .addComponent(jPasswordFieldContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelContraseñaIncorrecta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNoCuenta)
                    .addComponent(jLabelCrear)
                    .addComponent(jButtonIniciarSesion))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarSesionActionPerformed

        String usuarioIntroducido = this.jTextFieldUsuario.getText();
        boolean existe = false;
        char[] contraseñaUsuario = null;

        for (Usuario usuario : AccesoUsuario.usuarios) {

            if (usuario.getNombreUsuario().equalsIgnoreCase(usuarioIntroducido)) {

                setUsuarioLogeado(usuario);
                contraseñaUsuario = usuarioLogeado.getContraseña();
                existe = true;

            }

        }

        if (existe) {

            char[] contraseñaIntroducida = this.jPasswordFieldContraseña.getPassword();

            if (usuarioIntroducido.isEmpty() && contraseñaIntroducida.length == 0) {

                this.jLabelUsuarioIncorrecto.setText("Introduzca un nombre de usuario");
                this.jLabelContraseñaIncorrecta.setText("Introduzca una contraseña");

            } else if (!Arrays.equals(contraseñaIntroducida, contraseñaUsuario)) {

                this.jLabelUsuarioIncorrecto.setText(" ");
                this.jLabelContraseñaIncorrecta.setText("Contraseña incorrecta");

            } else if (!Arrays.equals(contraseñaIntroducida, contraseñaUsuario)) {

                this.jLabelUsuarioIncorrecto.setText(" ");
                this.   jLabelContraseñaIncorrecta.setText("Contraseña incorrecta");

            } else if (Arrays.equals(contraseñaIntroducida, contraseñaUsuario)) {

                this.dispose();

            }

            // Limpiar el arreglo de contraseñaIntroducida por seguridad
            Arrays.fill(contraseñaIntroducida, '\0');

        } else {
            this.jLabelUsuarioIncorrecto.setText("Usuario no encontrado");
        }

    }//GEN-LAST:event_jButtonIniciarSesionActionPerformed

    public static ArrayList<Usuario> getUsuarios() {
        return usuarios;
    }

    public static void setUsuarios(ArrayList<Usuario> usuarios) {
        AccesoUsuario.usuarios = usuarios;
    }

    public Usuario getUsuarioLogeado() {
        return usuarioLogeado;
    }

    public void setUsuarioLogeado(Usuario usuarioLogeado) {
        this.usuarioLogeado = usuarioLogeado;
    }

    private void jLabelCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCrearMouseClicked
        this.crearCuenta.setVisible(true);
    }//GEN-LAST:event_jLabelCrearMouseClicked

    private void jLabelCrearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCrearMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
        this.jLabelCrear.setForeground(new Color(255, 102, 0));
    }//GEN-LAST:event_jLabelCrearMouseEntered

    private void jLabelCrearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCrearMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        this.jLabelCrear.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_jLabelCrearMouseExited

    private void jButtonIniciarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIniciarSesionMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jButtonIniciarSesionMouseEntered

    private void jButtonIniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIniciarSesionMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jButtonIniciarSesionMouseExited

    private void jTextFieldUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioKeyPressed
        Controller.funcionBoton(evt, this.jButtonIniciarSesion);
    }//GEN-LAST:event_jTextFieldUsuarioKeyPressed

    private void jPasswordFieldContraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldContraseñaKeyPressed
        Controller.funcionBoton(evt, this.jButtonIniciarSesion);
    }//GEN-LAST:event_jPasswordFieldContraseñaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccesoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccesoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccesoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccesoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            AccesoUsuario dialog = new AccesoUsuario(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelContraseñaIncorrecta;
    private javax.swing.JLabel jLabelCrear;
    private javax.swing.JLabel jLabelNoCuenta;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabelUsuarioIncorrecto;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPasswordField jPasswordFieldContraseña;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
