package Main.Dialogs;

import Controllers.Controller;
import Entities.Usuario;
import java.awt.Cursor;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin e Iván
 */
public class CrearCuenta extends javax.swing.JDialog {

    /**
     * Creates new form CrearCuenta
     *
     * @param parent
     * @param modal
     */
    public CrearCuenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    private void funcionBoton() {
        // Reiniciar mensajes de error
        this.jLabeUsuarioObligatorio.setText("");
        this.jLabelContraseñaObligatorio.setText("");
        this.jLabelConfirmarContraseñaObligatorio.setText("");
        this.jLabelTelefonoObligatorio.setText("");
        this.jLabelProvinciaCiudadObligatorio.setText("");
        this.jLabelCalleObligatorio.setText("");

        // Validaciones
        boolean hasError = false;

        if (this.jTextFieldUsuario.getText().isEmpty()) {
            this.jLabeUsuarioObligatorio.setText("Este campo es obligatorio");
            hasError = true;
        }
        if (this.jPasswordFieldContraseña.getPassword().length == 0) {
            this.jLabelContraseñaObligatorio.setText("Este campo es obligatorio");
            hasError = true;
        }
        if (this.jPasswordFieldConfirmarContraseña.getPassword().length == 0) {
            this.jLabelConfirmarContraseñaObligatorio.setText("Este campo es obligatorio");
            hasError = true;
        }
        if (this.jTextFieldTelefono.getText().isEmpty()) {
            this.jLabelTelefonoObligatorio.setText("Este campo es obligatorio");
            hasError = true;
        }
        if (this.jTextFieldProvinciaCiudad.getText().isEmpty()) {
            this.jTextFieldProvinciaCiudad.setText("Este campo es obligatorio");
            hasError = true;
        }
        if (this.jTextFieldCalle.getText().isEmpty()) {
            this.jLabelCalleObligatorio.setText("Este campo es obligatorio");
            hasError = true;
        }

        if (hasError) {
            return;
        }

        // Validar contraseñas
        if (!Arrays.equals(this.jPasswordFieldContraseña.getPassword(), this.jPasswordFieldConfirmarContraseña.getPassword())) {
            this.jLabelConfirmarContraseñaObligatorio.setText("Contraseñas no coincidentes");
            return;
        }

        try {
            // Obtener datos del formulario
            String nombre = this.jTextFieldNombre.getText();
            String apellidos = this.jTextFieldApellidos.getText();
            String nombreUsuario = this.jTextFieldUsuario.getText();
            char[] contraseña = this.jPasswordFieldContraseña.getPassword();
            String email = this.jTextFieldEmail.getText();
            int telefono = Integer.parseInt(this.jTextFieldTelefono.getText());
            String provinciaCiudad = this.jTextFieldProvinciaCiudad.getText();
            String calle = this.jTextFieldCalle.getText();
            String pisoPuerta = this.jTextFieldPisoPuerta.getText();

            // Comprobar si el nombre de usuario ya existe
            for (Usuario u : AccesoUsuario.usuarios) {
                if (u.getNombreUsuario().equals(nombreUsuario)) {
                    JOptionPane.showMessageDialog(this, "El nombre de usuario ya está en uso.", "Error", JOptionPane.ERROR_MESSAGE); // Cambiar or Error (REVISAR)
                    return;
                }
            }

            // Crear el usuario
            Usuario usuario = new Usuario(nombre, apellidos, nombreUsuario, contraseña, email, telefono, provinciaCiudad, calle, pisoPuerta);

            // Agregar al acceso de usuarios
            AccesoUsuario.usuarios.add(usuario);

            // Cerrar ventana
            dispose();
        } catch (NumberFormatException e) {
            this.jTextFieldTelefono.setText("");
            JOptionPane.showMessageDialog(this, "El número de teléfono debe ser un valor numérico.", "Error", JOptionPane.ERROR_MESSAGE); // Cambiar or Error (REVISAR)
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApellidos = new javax.swing.JLabel();
        jTextFieldApellidos = new javax.swing.JTextField();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabelContraseña = new javax.swing.JLabel();
        jPasswordFieldContraseña = new javax.swing.JPasswordField();
        jLabelConfirmarContraseña = new javax.swing.JLabel();
        jPasswordFieldConfirmarContraseña = new javax.swing.JPasswordField();
        jLabelConfirmarContraseñaObligatorio = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabelProvinciaCiudad = new javax.swing.JLabel();
        jTextFieldProvinciaCiudad = new javax.swing.JTextField();
        jLabelCalle = new javax.swing.JLabel();
        jTextFieldCalle = new javax.swing.JTextField();
        jLabelPisoPuerta = new javax.swing.JLabel();
        jTextFieldPisoPuerta = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAceptar = new javax.swing.JButton();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jLabeUsuarioObligatorio = new javax.swing.JLabel();
        jLabelContraseñaObligatorio = new javax.swing.JLabel();
        jLabelTelefonoObligatorio = new javax.swing.JLabel();
        jLabelProvinciaCiudadObligatorio = new javax.swing.JLabel();
        jLabelCalleObligatorio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FastEat: Creación de cuenta");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabelTitulo.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 102, 0));
        jLabelTitulo.setText("CREACIÓN DE CUENTA");
        jLabelTitulo.setToolTipText("");

        jLabelNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(204, 204, 204));
        jLabelNombre.setText("Nombre");

        jTextFieldNombre.setBackground(new java.awt.Color(102, 102, 102));
        jTextFieldNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldNombre.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyPressed(evt);
            }
        });

        jLabelApellidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelApellidos.setForeground(new java.awt.Color(204, 204, 204));
        jLabelApellidos.setText("Apellidos");

        jTextFieldApellidos.setBackground(new java.awt.Color(102, 102, 102));
        jTextFieldApellidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldApellidos.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldApellidosKeyPressed(evt);
            }
        });

        jLabelUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(204, 204, 204));
        jLabelUsuario.setText("Usuario");

        jTextFieldUsuario.setBackground(new java.awt.Color(102, 102, 102));
        jTextFieldUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldUsuario.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldUsuarioKeyPressed(evt);
            }
        });

        jLabelContraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelContraseña.setForeground(new java.awt.Color(204, 204, 204));
        jLabelContraseña.setText("Contraseña");

        jPasswordFieldContraseña.setBackground(new java.awt.Color(102, 102, 102));
        jPasswordFieldContraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPasswordFieldContraseña.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordFieldContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldContraseñaKeyPressed(evt);
            }
        });

        jLabelConfirmarContraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelConfirmarContraseña.setForeground(new java.awt.Color(204, 204, 204));
        jLabelConfirmarContraseña.setText("Confirmar Contraseña");

        jPasswordFieldConfirmarContraseña.setBackground(new java.awt.Color(102, 102, 102));
        jPasswordFieldConfirmarContraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPasswordFieldConfirmarContraseña.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordFieldConfirmarContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldConfirmarContraseñaKeyPressed(evt);
            }
        });

        jLabelConfirmarContraseñaObligatorio.setForeground(new java.awt.Color(204, 51, 0));
        jLabelConfirmarContraseñaObligatorio.setText(" ");

        jLabelTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTelefono.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTelefono.setText("Teléfono");

        jTextFieldTelefono.setBackground(new java.awt.Color(102, 102, 102));
        jTextFieldTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldTelefono.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldTelefonoKeyPressed(evt);
            }
        });

        jLabelProvinciaCiudad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelProvinciaCiudad.setForeground(new java.awt.Color(204, 204, 204));
        jLabelProvinciaCiudad.setText("Provincia/Ciudad");

        jTextFieldProvinciaCiudad.setBackground(new java.awt.Color(102, 102, 102));
        jTextFieldProvinciaCiudad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldProvinciaCiudad.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldProvinciaCiudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldProvinciaCiudadKeyPressed(evt);
            }
        });

        jLabelCalle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCalle.setForeground(new java.awt.Color(204, 204, 204));
        jLabelCalle.setText("Calle");

        jTextFieldCalle.setBackground(new java.awt.Color(102, 102, 102));
        jTextFieldCalle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldCalle.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldCalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCalleKeyPressed(evt);
            }
        });

        jLabelPisoPuerta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPisoPuerta.setForeground(new java.awt.Color(204, 204, 204));
        jLabelPisoPuerta.setText("Piso/Puerta");

        jTextFieldPisoPuerta.setBackground(new java.awt.Color(102, 102, 102));
        jTextFieldPisoPuerta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldPisoPuerta.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldPisoPuerta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPisoPuertaKeyPressed(evt);
            }
        });

        jButtonCancelar.setBackground(new java.awt.Color(255, 102, 0));
        jButtonCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCancelar.setText("CANCELAR");
        jButtonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonCancelarMouseExited(evt);
            }
        });
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonAceptar.setBackground(new java.awt.Color(255, 102, 0));
        jButtonAceptar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAceptar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAceptar.setText("ACEPTAR");
        jButtonAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAceptarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAceptarMouseExited(evt);
            }
        });
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        jButtonAceptar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonAceptarKeyPressed(evt);
            }
        });

        jTextFieldEmail.setBackground(new java.awt.Color(102, 102, 102));
        jTextFieldEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldEmail.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldEmailKeyPressed(evt);
            }
        });

        jLabelEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(204, 204, 204));
        jLabelEmail.setText("Email");

        jLabeUsuarioObligatorio.setForeground(new java.awt.Color(204, 51, 0));
        jLabeUsuarioObligatorio.setText(" ");

        jLabelContraseñaObligatorio.setForeground(new java.awt.Color(204, 51, 0));
        jLabelContraseñaObligatorio.setText(" ");

        jLabelTelefonoObligatorio.setForeground(new java.awt.Color(204, 51, 0));
        jLabelTelefonoObligatorio.setText(" ");

        jLabelProvinciaCiudadObligatorio.setForeground(new java.awt.Color(204, 51, 0));
        jLabelProvinciaCiudadObligatorio.setText(" ");

        jLabelCalleObligatorio.setForeground(new java.awt.Color(204, 51, 0));
        jLabelCalleObligatorio.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelEmail)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNombre)
                                    .addComponent(jLabelApellidos)
                                    .addComponent(jLabelUsuario)
                                    .addComponent(jLabelContraseña)
                                    .addComponent(jLabelConfirmarContraseña)
                                    .addComponent(jLabelTelefono)
                                    .addComponent(jLabelProvinciaCiudad)
                                    .addComponent(jLabelCalle)
                                    .addComponent(jLabelPisoPuerta))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTextFieldTelefono)
                                                .addComponent(jTextFieldProvinciaCiudad)
                                                .addComponent(jTextFieldCalle)
                                                .addComponent(jPasswordFieldConfirmarContraseña, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jTextFieldPisoPuerta)
                                                .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                                                .addComponent(jTextFieldEmail)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(6, 6, 6)
                                                    .addComponent(jLabelConfirmarContraseñaObligatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addComponent(jLabelTelefonoObligatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabelProvinciaCiudadObligatorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabelCalleObligatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jPasswordFieldContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 1, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelContraseñaObligatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabeUsuarioObligatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(40, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombre))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelApellidos))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabeUsuarioObligatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelContraseña))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelContraseñaObligatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldConfirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelConfirmarContraseña))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelConfirmarContraseñaObligatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelefono))
                .addGap(7, 7, 7)
                .addComponent(jLabelTelefonoObligatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmail))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldProvinciaCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProvinciaCiudad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelProvinciaCiudadObligatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCalle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCalleObligatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPisoPuerta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPisoPuerta))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonCancelar))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        funcionBoton();
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCancelarMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jButtonCancelarMouseEntered

    private void jButtonCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCancelarMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jButtonCancelarMouseExited

    private void jButtonAceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAceptarMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jButtonAceptarMouseEntered

    private void jButtonAceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAceptarMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jButtonAceptarMouseExited

    private void jButtonAceptarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonAceptarKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            funcionBoton();
        }
    }//GEN-LAST:event_jButtonAceptarKeyPressed

    private void jTextFieldNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyPressed
        Controller.funcionBoton(evt, this.jButtonAceptar);
    }//GEN-LAST:event_jTextFieldNombreKeyPressed

    private void jTextFieldApellidosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApellidosKeyPressed
        Controller.funcionBoton(evt, this.jButtonAceptar);
    }//GEN-LAST:event_jTextFieldApellidosKeyPressed

    private void jTextFieldUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioKeyPressed
        Controller.funcionBoton(evt, this.jButtonAceptar);
    }//GEN-LAST:event_jTextFieldUsuarioKeyPressed

    private void jPasswordFieldContraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldContraseñaKeyPressed
        Controller.funcionBoton(evt, this.jButtonAceptar);
    }//GEN-LAST:event_jPasswordFieldContraseñaKeyPressed

    private void jPasswordFieldConfirmarContraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldConfirmarContraseñaKeyPressed
        Controller.funcionBoton(evt, this.jButtonAceptar);
    }//GEN-LAST:event_jPasswordFieldConfirmarContraseñaKeyPressed

    private void jTextFieldTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoKeyPressed
        Controller.funcionBoton(evt, this.jButtonAceptar);
    }//GEN-LAST:event_jTextFieldTelefonoKeyPressed

    private void jTextFieldEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailKeyPressed
        Controller.funcionBoton(evt, this.jButtonAceptar);
    }//GEN-LAST:event_jTextFieldEmailKeyPressed

    private void jTextFieldProvinciaCiudadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProvinciaCiudadKeyPressed
        Controller.funcionBoton(evt, this.jButtonAceptar);
    }//GEN-LAST:event_jTextFieldProvinciaCiudadKeyPressed

    private void jTextFieldCalleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCalleKeyPressed
        Controller.funcionBoton(evt, this.jButtonAceptar);
    }//GEN-LAST:event_jTextFieldCalleKeyPressed

    private void jTextFieldPisoPuertaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPisoPuertaKeyPressed
        Controller.funcionBoton(evt, this.jButtonAceptar);
    }//GEN-LAST:event_jTextFieldPisoPuertaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            CrearCuenta dialog = new CrearCuenta(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabeUsuarioObligatorio;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelCalle;
    private javax.swing.JLabel jLabelCalleObligatorio;
    private javax.swing.JLabel jLabelConfirmarContraseña;
    private javax.swing.JLabel jLabelConfirmarContraseñaObligatorio;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelContraseñaObligatorio;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPisoPuerta;
    private javax.swing.JLabel jLabelProvinciaCiudad;
    private javax.swing.JLabel jLabelProvinciaCiudadObligatorio;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTelefonoObligatorio;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldConfirmarContraseña;
    private javax.swing.JPasswordField jPasswordFieldContraseña;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldCalle;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPisoPuerta;
    private javax.swing.JTextField jTextFieldProvinciaCiudad;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
