
package Unidad01.ListaEjercicios.Ejercicio08;

import Unidad01.Ejemplo04.ClickListener;

/**
 *
 * @author kgv17
 */
public class Acciones2 extends javax.swing.JPanel {
    
    private Resultados2 r;
    
    /**
     * Creates new form Acciones
     */
    public Acciones2() {
        r = new Resultados2();
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAcciones01 = new javax.swing.JPanel();
        jCheckBoxLeer = new javax.swing.JCheckBox();
        jCheckBoxEscalada = new javax.swing.JCheckBox();
        jCheckBoxEsquiar = new javax.swing.JCheckBox();
        jCheckBoxSubmarinismo = new javax.swing.JCheckBox();

        setPreferredSize(new java.awt.Dimension(600, 260));

        jPanelAcciones01.setPreferredSize(new java.awt.Dimension(600, 220));

        jCheckBoxLeer.setText("Leer");
        jCheckBoxLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxLeerActionPerformed(evt);
            }
        });

        jCheckBoxEscalada.setText("Escalada");
        jCheckBoxEscalada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEscaladaActionPerformed(evt);
            }
        });

        jCheckBoxEsquiar.setText("Esquiar");
        jCheckBoxEsquiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEsquiarActionPerformed(evt);
            }
        });

        jCheckBoxSubmarinismo.setText("Submarinismo");
        jCheckBoxSubmarinismo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSubmarinismoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAcciones01Layout = new javax.swing.GroupLayout(jPanelAcciones01);
        jPanelAcciones01.setLayout(jPanelAcciones01Layout);
        jPanelAcciones01Layout.setHorizontalGroup(
            jPanelAcciones01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAcciones01Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(jPanelAcciones01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxEsquiar)
                    .addComponent(jCheckBoxLeer))
                .addGap(122, 122, 122)
                .addGroup(jPanelAcciones01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxSubmarinismo)
                    .addComponent(jCheckBoxEscalada))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        jPanelAcciones01Layout.setVerticalGroup(
            jPanelAcciones01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAcciones01Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelAcciones01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxLeer)
                    .addComponent(jCheckBoxEscalada))
                .addGap(37, 37, 37)
                .addGroup(jPanelAcciones01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxEsquiar)
                    .addComponent(jCheckBoxSubmarinismo))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAcciones01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanelAcciones01, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxLeerActionPerformed
        r.agregarDato("Leer");
    }//GEN-LAST:event_jCheckBoxLeerActionPerformed

    private void jCheckBoxEscaladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEscaladaActionPerformed
        r.agregarDato("Escalada");
    }//GEN-LAST:event_jCheckBoxEscaladaActionPerformed

    private void jCheckBoxEsquiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEsquiarActionPerformed
        r.agregarDato("Esquiar");
    }//GEN-LAST:event_jCheckBoxEsquiarActionPerformed

    private void jCheckBoxSubmarinismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSubmarinismoActionPerformed
        r.agregarDato("Submarinismo");
    }//GEN-LAST:event_jCheckBoxSubmarinismoActionPerformed
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxEscalada;
    private javax.swing.JCheckBox jCheckBoxEsquiar;
    private javax.swing.JCheckBox jCheckBoxLeer;
    private javax.swing.JCheckBox jCheckBoxSubmarinismo;
    private javax.swing.JPanel jPanelAcciones01;
    // End of variables declaration//GEN-END:variables
}
