
package Unidad01.ListaEjercicios.Ejercicio08;


/**
 *
 * @author kgv17
 */
public class Acciones1 extends javax.swing.JPanel {

    /**
     * Creates new form Acciones
     */
    public Acciones1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAcciones01 = new javax.swing.JPanel();
        jButtonB4 = new javax.swing.JButton();
        jButtonB3 = new javax.swing.JButton();
        jButtonB2 = new javax.swing.JButton();
        jButtonB1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 260));

        jPanelAcciones01.setPreferredSize(new java.awt.Dimension(600, 220));

        jButtonB4.setText("B4");
        jButtonB4.setMaximumSize(new java.awt.Dimension(50, 23));
        jButtonB4.setMinimumSize(new java.awt.Dimension(50, 23));
        jButtonB4.setPreferredSize(new java.awt.Dimension(50, 23));
        jButtonB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonB4ActionPerformed(evt);
            }
        });

        jButtonB3.setText("B3");
        jButtonB3.setMaximumSize(new java.awt.Dimension(50, 23));
        jButtonB3.setMinimumSize(new java.awt.Dimension(50, 23));
        jButtonB3.setPreferredSize(new java.awt.Dimension(50, 23));
        jButtonB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonB3ActionPerformed(evt);
            }
        });

        jButtonB2.setText("B2");
        jButtonB2.setMaximumSize(new java.awt.Dimension(50, 23));
        jButtonB2.setMinimumSize(new java.awt.Dimension(50, 23));
        jButtonB2.setPreferredSize(new java.awt.Dimension(50, 23));
        jButtonB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonB2ActionPerformed(evt);
            }
        });

        jButtonB1.setText("B1");
        jButtonB1.setMaximumSize(new java.awt.Dimension(50, 23));
        jButtonB1.setMinimumSize(new java.awt.Dimension(50, 23));
        jButtonB1.setPreferredSize(new java.awt.Dimension(50, 23));
        jButtonB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonB1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAcciones01Layout = new javax.swing.GroupLayout(jPanelAcciones01);
        jPanelAcciones01.setLayout(jPanelAcciones01Layout);
        jPanelAcciones01Layout.setHorizontalGroup(
            jPanelAcciones01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAcciones01Layout.createSequentialGroup()
                .addContainerGap(173, Short.MAX_VALUE)
                .addComponent(jButtonB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonB4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );
        jPanelAcciones01Layout.setVerticalGroup(
            jPanelAcciones01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAcciones01Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanelAcciones01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonB4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAcciones01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanelAcciones01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonB1ActionPerformed

    private void jButtonB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonB2ActionPerformed

    private void jButtonB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonB3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonB3ActionPerformed

    private void jButtonB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonB4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonB4ActionPerformed
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonB1;
    private javax.swing.JButton jButtonB2;
    private javax.swing.JButton jButtonB3;
    private javax.swing.JButton jButtonB4;
    private javax.swing.JPanel jPanelAcciones01;
    // End of variables declaration//GEN-END:variables
}
