
package Unidad01.ListaEjercicios.Ejercicio08;

import java.awt.BorderLayout;

/**
 *
 * @author kgv17
 */
public class Resultados extends javax.swing.JPanel {

    /**
     * Creates new form Resultados
     */
    public Resultados() {
        initComponents();
        
        Resultados1 r = new Resultados1();
        r.setSize(600, 260);

        jPanelResultados.removeAll();
        jPanelResultados.add(r, BorderLayout.CENTER);
        jPanelResultados.revalidate();
        jPanelResultados.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelCambiarResultados = new javax.swing.JLabel();
        jComboBoxResultados = new javax.swing.JComboBox<>();
        jPanelResultados = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(600, 260));

        jPanel1.setBackground(new java.awt.Color(0, 204, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 40));

        jLabelCambiarResultados.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabelCambiarResultados.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCambiarResultados.setText("Cambiar resultados:");

        jComboBoxResultados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pulsaciones", "Selecciones", " " }));
        jComboBoxResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxResultadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(jLabelCambiarResultados)
                .addGap(48, 48, 48)
                .addComponent(jComboBoxResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCambiarResultados)
                    .addComponent(jComboBoxResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanelResultados.setMaximumSize(new java.awt.Dimension(600, 220));
        jPanelResultados.setMinimumSize(new java.awt.Dimension(600, 220));
        jPanelResultados.setPreferredSize(new java.awt.Dimension(600, 220));

        javax.swing.GroupLayout jPanelResultadosLayout = new javax.swing.GroupLayout(jPanelResultados);
        jPanelResultados.setLayout(jPanelResultadosLayout);
        jPanelResultadosLayout.setHorizontalGroup(
            jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanelResultadosLayout.setVerticalGroup(
            jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelResultados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(jPanelResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxResultadosActionPerformed
         // Limpiar el panel antes de agregar nuevos componentes
        jPanelResultados.removeAll();

        if ("Selecciones".equals(jComboBoxResultados.getSelectedItem().toString())) {
            // Crear una nueva instancia de Resultados2
            Resultados2 r = new Resultados2();
            r.setSize(600, 220);
            jPanelResultados.setLayout(new BorderLayout()); // Asegúrate de usar un layout adecuado
            jPanelResultados.add(r, BorderLayout.CENTER); // Agregar el nuevo panel
        } else {
            Resultados1 r = new Resultados1();
            r.setSize(600, 220);
            jPanelResultados.setLayout(new BorderLayout()); // Asegúrate de usar un layout adecuado
            jPanelResultados.add(r, BorderLayout.CENTER); // Agregar el nuevo panel
        }

        // Actualizar el panel
        jPanelResultados.revalidate();
        jPanelResultados.repaint();
    }//GEN-LAST:event_jComboBoxResultadosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxResultados;
    private javax.swing.JLabel jLabelCambiarResultados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelResultados;
    // End of variables declaration//GEN-END:variables
}
